import React, { useEffect, useRef } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
// import './MapComponent.css';

const MapComponent = () => {
    const mapRef = useRef(null);

    useEffect(() => {
        if (!mapRef.current) return;

        // Base layers
        const osm = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
            minZoom: 2,
            maxZoom: 15
        });

        const cartodb = L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, &copy; <a href="http://cartodb.com/attributions">CartoDB</a>',
            minZoom: 2,
            maxZoom: 15
        });

        const toner = L.tileLayer('http://{s}.tile.stamen.com/toner/{z}/{x}/{y}.png', {
            attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.',
            minZoom: 2,
            maxZoom: 15
        });

        // const white = L.tileLayer("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEAAQMAAABmvDolAAAAA1BMVEX///+nxBvIAAAAH0lEQVQYGe3BAQ0AAADCIPunfg43YAAAAAAAAAAA5wIhAAAB9aK9BAAAAABJRU5ErkJggg==", {
        //     minZoom: 2,
        //     maxZoom: 15
        // });

        // Overlay layers (TMS)
        const lyr = L.tileLayer('./{z}/{x}/{y}.png', {
            tms: 0,
            opacity: 0.7,
            attribution: "",
            minZoom: 2,
            maxZoom: 15
        });

        // Initialize map
        const map = L.map(mapRef.current, {
            center: [7.567989373982208, -5.584823439334766],
            zoom: 15,
            minZoom: 2,
            maxZoom: 15,
            layers: [osm]
        });

        const basemaps = {
            "OpenStreetMap": osm,
            "CartoDB Positron": cartodb,
            "Stamen Toner": toner,
            // "Without background": white
        };

        const overlaymaps = {
            "Layer": lyr
        };

        // Add title control
        const titleControl = L.control();
        titleControl.onAdd = function() {
            const div = L.DomUtil.create('div', 'ctl title');
            div.innerHTML = "ocs2020.tif";
            return div;
        };
        titleControl.addTo(map);

        // Add note control
        const src = 'Generated by <a href="https://gdal.org/programs/gdal2tiles.html">GDAL2Tiles</a>, Copyright &copy; 2008 <a href="http://www.klokan.cz/">Klokan Petr Pridal</a>,  <a href="https://gdal.org">GDAL</a> &amp; <a href="http://www.osgeo.org/">OSGeo</a> <a href="http://code.google.com/soc/">GSoC</a>';
        const noteControl = L.control({ position: 'bottomleft' });
        noteControl.onAdd = function() {
            const div = L.DomUtil.create('div', 'ctl src');
            div.innerHTML = src;
            return div;
        };
        noteControl.addTo(map);

        // Add layer control
        L.control.layers(basemaps, overlaymaps, { collapsed: false }).addTo(map);

        // Fit bounds
        map.fitBounds([
            [4.339646555391203, -2.4846305941511115],
            [10.796332192573212, -8.68501628451842]
        ]);

        // Cleanup on unmount
        return () => {
            map.remove();
        };
    }, []);

    return <div ref={mapRef} id="map" />;
};

export default MapComponent;